<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        City::create(['departament_id' => 1, 'name' => 'EL ENCANTO', 'code' => '91263']);
        City::create(['departament_id' => 1, 'name' => 'LA CHORRERA', 'code' => '91405']);
        City::create(['departament_id' => 1, 'name' => 'LA PEDRERA', 'code' => '91407']);
        City::create(['departament_id' => 1, 'name' => 'LA VICTORIA', 'code' => '91430']);
        City::create(['departament_id' => 1, 'name' => 'LETICIA', 'code' => '91001']);
        City::create(['departament_id' => 1, 'name' => 'MIRITI - PARANA', 'code' => '91460']);
        City::create(['departament_id' => 1, 'name' => 'PUERTO ALEGRIA', 'code' => '91530']);
        City::create(['departament_id' => 1, 'name' => 'PUERTO ARICA', 'code' => '91536']);
        City::create(['departament_id' => 1, 'name' => 'PUERTO NARIÑO', 'code' => '91540']);
        City::create(['departament_id' => 1, 'name' => 'PUERTO SANTANDER', 'code' => '91669']);
        City::create(['departament_id' => 1, 'name' => 'TARAPACA', 'code' => '91798']);

        City::create(['departament_id' => 2, 'name' => 'CÁCERES', 'code' => '05120']);
        City::create(['departament_id' => 2, 'name' => 'CAUCASIA', 'code' => '05154']);
        City::create(['departament_id' => 2, 'name' => 'EL BAGRE', 'code' => '05250']);
        City::create(['departament_id' => 2, 'name' => 'NECHÍ', 'code' => '05495']);
        City::create(['departament_id' => 2, 'name' => 'TARAZÁ', 'code' => '05790']);
        City::create(['departament_id' => 2, 'name' => 'ZARAGOZA', 'code' => '05895']);
        City::create(['departament_id' => 2, 'name' => 'CARACOLÍ', 'code' => '05142']);
        City::create(['departament_id' => 2, 'name' => 'MACEO', 'code' => '05425']);
        City::create(['departament_id' => 2, 'name' => 'PUERTO BERRÍO', 'code' => '05579']);
        City::create(['departament_id' => 2, 'name' => 'PUERTO NARE', 'code' => '05585']);
        City::create(['departament_id' => 2, 'name' => 'PUERTO TRIUNFO', 'code' => '05591']);
        City::create(['departament_id' => 2, 'name' => 'YONDÓ', 'code' => '05893']);
        City::create(['departament_id' => 2, 'name' => 'AMALFI', 'code' => '05031']);
        City::create(['departament_id' => 2, 'name' => 'ANORÍ', 'code' => '05040']);
        City::create(['departament_id' => 2, 'name' => 'CISNEROS', 'code' => '05190']);
        City::create(['departament_id' => 2, 'name' => 'REMEDIOS', 'code' => '05604']);
        City::create(['departament_id' => 2, 'name' => 'SAN ROQUE', 'code' => '05670']);
        City::create(['departament_id' => 2, 'name' => 'SANTO DOMINGO', 'code' => '05690']);
        City::create(['departament_id' => 2, 'name' => 'SEGOVIA', 'code' => '05736']);
        City::create(['departament_id' => 2, 'name' => 'VEGACHÍ', 'code' => '05858']);
        City::create(['departament_id' => 2, 'name' => 'YALÍ', 'code' => '05885']);
        City::create(['departament_id' => 2, 'name' => 'YOLOMBÓ', 'code' => '05890']);
        City::create(['departament_id' => 2, 'name' => 'ANGOSTURA', 'code' => '05038']);
        City::create(['departament_id' => 2, 'name' => 'BELMIRA', 'code' => '05086']);
        City::create(['departament_id' => 2, 'name' => 'BRICEÑO', 'code' => '05107']);
        City::create(['departament_id' => 2, 'name' => 'CAMPAMENTO', 'code' => '05134']);
        City::create(['departament_id' => 2, 'name' => 'CAROLINA', 'code' => '05150']);
        City::create(['departament_id' => 2, 'name' => 'DON MATÍAS', 'code' => '05237']);
        City::create(['departament_id' => 2, 'name' => 'ENTRERRÍOS', 'code' => '05264']);
        City::create(['departament_id' => 2, 'name' => 'GÓMEZ PLATA', 'code' => '05310']);
        City::create(['departament_id' => 2, 'name' => 'GUADALUPE', 'code' => '05315']);
        City::create(['departament_id' => 2, 'name' => 'ITUANGO', 'code' => '05361']);
        City::create(['departament_id' => 2, 'name' => 'SAN ANDRÉS', 'code' => '05647']);
        City::create(['departament_id' => 2, 'name' => 'SAN JOSÉ DE LA MONTAÑA', 'code' => '05658']);
        City::create(['departament_id' => 2, 'name' => 'SAN PEDRO', 'code' => '05664']);
        City::create(['departament_id' => 2, 'name' => 'SANTA ROSA DE OSOS', 'code' => '05686']);
        City::create(['departament_id' => 2, 'name' => 'TOLEDO', 'code' => '05819']);
        City::create(['departament_id' => 2, 'name' => 'VALDIVIA', 'code' => '05854']);
        City::create(['departament_id' => 2, 'name' => 'YARUMAL', 'code' => '05887']);
        City::create(['departament_id' => 2, 'name' => 'ABRIAQUÍ', 'code' => '05004']);
        City::create(['departament_id' => 2, 'name' => 'ANZA', 'code' => '05044']);
        City::create(['departament_id' => 2, 'name' => 'ARMENIA', 'code' => '05059']);
        City::create(['departament_id' => 2, 'name' => 'BURITICÁ', 'code' => '05113']);
        City::create(['departament_id' => 2, 'name' => 'CAÑASGORDAS', 'code' => '05138']);
        City::create(['departament_id' => 2, 'name' => 'DABEIBA', 'code' => '05234']);
        City::create(['departament_id' => 2, 'name' => 'EBÉJICO', 'code' => '05240']);
        City::create(['departament_id' => 2, 'name' => 'FRONTINO', 'code' => '05284']);
        City::create(['departament_id' => 2, 'name' => 'GIRALDO', 'code' => '05306']);
        City::create(['departament_id' => 2, 'name' => 'HELICONIA', 'code' => '05347']);
        City::create(['departament_id' => 2, 'name' => 'LIBORINA', 'code' => '05411']);
        City::create(['departament_id' => 2, 'name' => 'OLAYA', 'code' => '05501']);
        City::create(['departament_id' => 2, 'name' => 'PEQUE', 'code' => '05543']);
        City::create(['departament_id' => 2, 'name' => 'SABANALARGA', 'code' => '05628']);
        City::create(['departament_id' => 2, 'name' => 'SAN JERÓNIMO', 'code' => '05656']);
        City::create(['departament_id' => 2, 'name' => 'SANTAFÉ DE ANTIOQUIA', 'code' => '05042']);
        City::create(['departament_id' => 2, 'name' => 'SOPETRÁN', 'code' => '05761']);
        City::create(['departament_id' => 2, 'name' => 'URAMITA', 'code' => '05842']);
        City::create(['departament_id' => 2, 'name' => 'ABEJORRAL', 'code' => '05002']);
        City::create(['departament_id' => 2, 'name' => 'ALEJANDRÍA', 'code' => '05021']);
        City::create(['departament_id' => 2, 'name' => 'ARGELIA', 'code' => '05055']);
        City::create(['departament_id' => 2, 'name' => 'CARMEN DE VIBORAL', 'code' => '05148']);
        City::create(['departament_id' => 2, 'name' => 'COCORNÁ', 'code' => '05197']);
        City::create(['departament_id' => 2, 'name' => 'CONCEPCIÓN', 'code' => '05206']);
        City::create(['departament_id' => 2, 'name' => 'GRANADA', 'code' => '05313']);
        City::create(['departament_id' => 2, 'name' => 'GUARNE', 'code' => '05318']);
        City::create(['departament_id' => 2, 'name' => 'GUATAPE', 'code' => '05321']);
        City::create(['departament_id' => 2, 'name' => 'LA CEJA', 'code' => '05376']);
        City::create(['departament_id' => 2, 'name' => 'LA UNIÓN', 'code' => '05400']);
        City::create(['departament_id' => 2, 'name' => 'MARINILLA', 'code' => '05440']);
        City::create(['departament_id' => 2, 'name' => 'NARIÑO', 'code' => '05483']);
        City::create(['departament_id' => 2, 'name' => 'PEÑOL', 'code' => '05541']);
        City::create(['departament_id' => 2, 'name' => 'RETIRO', 'code' => '05607']);
        City::create(['departament_id' => 2, 'name' => 'RIONEGRO', 'code' => '05615']);
        City::create(['departament_id' => 2, 'name' => 'SAN CARLOS', 'code' => '05649']);
        City::create(['departament_id' => 2, 'name' => 'SAN FRANCISCO', 'code' => '05652']);
        City::create(['departament_id' => 2, 'name' => 'SAN LUIS', 'code' => '05660']);
        City::create(['departament_id' => 2, 'name' => 'SAN RAFAEL', 'code' => '05667']);
        City::create(['departament_id' => 2, 'name' => 'SAN VICENTE', 'code' => '05674']);
        City::create(['departament_id' => 2, 'name' => 'SANTUARIO', 'code' => '05697']);
        City::create(['departament_id' => 2, 'name' => 'SONSON', 'code' => '05756']);
        City::create(['departament_id' => 2, 'name' => 'AMAGÁ', 'code' => '05030']);
        City::create(['departament_id' => 2, 'name' => 'ANDES', 'code' => '05034']);
        City::create(['departament_id' => 2, 'name' => 'ANGELOPOLIS', 'code' => '05036']);
        City::create(['departament_id' => 2, 'name' => 'BETANIA', 'code' => '05091']);
        City::create(['departament_id' => 2, 'name' => 'BETULIA', 'code' => '05093']);
        City::create(['departament_id' => 2, 'name' => 'CAICEDO', 'code' => '05125']);
        City::create(['departament_id' => 2, 'name' => 'CARAMANTA', 'code' => '05145']);
        City::create(['departament_id' => 2, 'name' => 'CIUDAD BOLÍVAR', 'code' => '05101']);
        City::create(['departament_id' => 2, 'name' => 'CONCORDIA', 'code' => '05209']);
        City::create(['departament_id' => 2, 'name' => 'FREDONIA', 'code' => '05282']);
        City::create(['departament_id' => 2, 'name' => 'HISPANIA', 'code' => '05353']);
        City::create(['departament_id' => 2, 'name' => 'JARDÍN', 'code' => '05364']);
        City::create(['departament_id' => 2, 'name' => 'JERICÓ', 'code' => '05368']);
        City::create(['departament_id' => 2, 'name' => 'LA PINTADA', 'code' => '05390']);
        City::create(['departament_id' => 2, 'name' => 'MONTEBELLO', 'code' => '05467']);
        City::create(['departament_id' => 2, 'name' => 'PUEBLORRICO', 'code' => '05576']);
        City::create(['departament_id' => 2, 'name' => 'SALGAR', 'code' => '05642']);
        City::create(['departament_id' => 2, 'name' => 'SANTA BÁRBARA', 'code' => '05679']);
        City::create(['departament_id' => 2, 'name' => 'TÁMESIS', 'code' => '05789']);
        City::create(['departament_id' => 2, 'name' => 'TARSO', 'code' => '05792']);
        City::create(['departament_id' => 2, 'name' => 'TITIRIBÍ', 'code' => '05809']);
        City::create(['departament_id' => 2, 'name' => 'URRAO', 'code' => '05847']);
        City::create(['departament_id' => 2, 'name' => 'VALPARAÍSO', 'code' => '05856']);
        City::create(['departament_id' => 2, 'name' => 'VENECIA', 'code' => '05861']);
        City::create(['departament_id' => 2, 'name' => 'APARTADÓ', 'code' => '05045']);
        City::create(['departament_id' => 2, 'name' => 'ARBOLETES', 'code' => '05051']);
        City::create(['departament_id' => 2, 'name' => 'CAREPA', 'code' => '05147']);
        City::create(['departament_id' => 2, 'name' => 'CHIGORODÓ', 'code' => '05172']);
        City::create(['departament_id' => 2, 'name' => 'MURINDÓ', 'code' => '05475']);
        City::create(['departament_id' => 2, 'name' => 'MUTATÁ', 'code' => '05480']);
        City::create(['departament_id' => 2, 'name' => 'NECOCLÍ', 'code' => '05490']);
        City::create(['departament_id' => 2, 'name' => 'SAN JUAN DE URABÁ', 'code' => '05659']);
        City::create(['departament_id' => 2, 'name' => 'SAN PEDRO DE URABÁ', 'code' => '05665']);
        City::create(['departament_id' => 2, 'name' => 'TURBO', 'code' => '05837']);
        City::create(['departament_id' => 2, 'name' => 'VIGÍA DEL FUERTE', 'code' => '05873']);
        City::create(['departament_id' => 2, 'name' => 'BARBOSA', 'code' => '05079']);
        City::create(['departament_id' => 2, 'name' => 'BELLO', 'code' => '05088']);
        City::create(['departament_id' => 2, 'name' => 'CALDAS', 'code' => '05129']);
        City::create(['departament_id' => 2, 'name' => 'COPACABANA', 'code' => '05212']);
        City::create(['departament_id' => 2, 'name' => 'ENVIGADO', 'code' => '05266']);
        City::create(['departament_id' => 2, 'name' => 'GIRARDOTA', 'code' => '05308']);
        City::create(['departament_id' => 2, 'name' => 'ITAGÜÍ', 'code' => '05360']);
        City::create(['departament_id' => 2, 'name' => 'LA ESTRELLA', 'code' => '05380']);
        City::create(['departament_id' => 2, 'name' => 'MEDELLÍN', 'code' => '05001']);
        City::create(['departament_id' => 2, 'name' => 'SABANETA', 'code' => '05631']);

        City::create(['departament_id' => 3, 'name' => 'ARAUCA', 'code' => '81001']);
        City::create(['departament_id' => 3, 'name' => 'ARAUQUITA', 'code' => '81065']);
        City::create(['departament_id' => 3, 'name' => 'CRAVO NORTE', 'code' => '81220']);
        City::create(['departament_id' => 3, 'name' => 'FORTUL', 'code' => '81300']);
        City::create(['departament_id' => 3, 'name' => 'PUERTO RONDÓN', 'code' => '81591']);
        City::create(['departament_id' => 3, 'name' => 'SARAVENA', 'code' => '81736']);
        City::create(['departament_id' => 3, 'name' => 'TAME', 'code' => '81794']);

        City::create(['departament_id' => 4, 'name' => 'PROVIDENCIA Y SANTA CATALINA', 'code' => '88564']);
        City::create(['departament_id' => 4, 'name' => 'SAN ANDRÉS', 'code' => '88001']);

        City::create(['departament_id' => 5, 'name' => 'BARRANQUILLA', 'code' => '08001']);
        City::create(['departament_id' => 5, 'name' => 'GALAPA', 'code' => '08296']);
        City::create(['departament_id' => 5, 'name' => 'MALAMBO', 'code' => '08433']);
        City::create(['departament_id' => 5, 'name' => 'PUERTO COLOMBIA', 'code' => '08573']);
        City::create(['departament_id' => 5, 'name' => 'SOLEDAD', 'code' => '08758']);
        City::create(['departament_id' => 5, 'name' => 'CAMPO DE LA CRUZ', 'code' => '08137']);
        City::create(['departament_id' => 5, 'name' => 'CANDELARIA', 'code' => '08141']);
        City::create(['departament_id' => 5, 'name' => 'LURUACO', 'code' => '08421']);
        City::create(['departament_id' => 5, 'name' => 'MANATÍ', 'code' => '08436']);
        City::create(['departament_id' => 5, 'name' => 'REPELÓN', 'code' => '08606']);
        City::create(['departament_id' => 5, 'name' => 'SANTA LUCÍA', 'code' => '08675']);
        City::create(['departament_id' => 5, 'name' => 'SUÁN', 'code' => '08770']);
        City::create(['departament_id' => 5, 'name' => 'BARANOA', 'code' => '08078']);
        City::create(['departament_id' => 5, 'name' => 'PALMAR DE VARELA', 'code' => '08520']);
        City::create(['departament_id' => 5, 'name' => 'POLONUEVO', 'code' => '08558']);
        City::create(['departament_id' => 5, 'name' => 'PONEDERA', 'code' => '08560']);
        City::create(['departament_id' => 5, 'name' => 'SABANAGRANDE', 'code' => '08634']);
        City::create(['departament_id' => 5, 'name' => 'SABANALARGA', 'code' => '08638']);
        City::create(['departament_id' => 5, 'name' => 'SANTO TOMÁS', 'code' => '08685']);
        City::create(['departament_id' => 5, 'name' => 'JUAN DE ACOSTA', 'code' => '08372']);
        City::create(['departament_id' => 5, 'name' => 'PIOJÓ', 'code' => '08549']);
        City::create(['departament_id' => 5, 'name' => 'TUBARÁ', 'code' => '08832']);
        City::create(['departament_id' => 5, 'name' => 'USIACURÍ', 'code' => '08849']);

        City::create(['departament_id' => 6, 'name' => 'CICUCO', 'code' => '13188']);
        City::create(['departament_id' => 6, 'name' => 'HATILLO DE LOBA', 'code' => '13300']);
        City::create(['departament_id' => 6, 'name' => 'MARGARITA', 'code' => '13440']);
        City::create(['departament_id' => 6, 'name' => 'MOMPÓS', 'code' => '13468']);
        City::create(['departament_id' => 6, 'name' => 'SAN FERNANDO', 'code' => '13650']);
        City::create(['departament_id' => 6, 'name' => 'TALAIGUA NUEVO', 'code' => '13780']);
        City::create(['departament_id' => 6, 'name' => 'ARJONA', 'code' => '13052']);
        City::create(['departament_id' => 6, 'name' => 'ARROYOHONDO', 'code' => '13062']);
        City::create(['departament_id' => 6, 'name' => 'CALAMAR', 'code' => '13140']);
        City::create(['departament_id' => 6, 'name' => 'CARTAGENA', 'code' => '13001']);
        City::create(['departament_id' => 6, 'name' => 'CLEMENCIA', 'code' => '13222']);
        City::create(['departament_id' => 6, 'name' => 'MAHATES', 'code' => '13433']);
        City::create(['departament_id' => 6, 'name' => 'SAN CRISTOBAL', 'code' => '13620']);
        City::create(['departament_id' => 6, 'name' => 'SAN ESTANISLAO', 'code' => '13647']);
        City::create(['departament_id' => 6, 'name' => 'SANTA CATALINA', 'code' => '13673']);
        City::create(['departament_id' => 6, 'name' => 'SANTA ROSA DE LIMA', 'code' => '13683']);
        City::create(['departament_id' => 6, 'name' => 'SOPLAVIENTO', 'code' => '13760']);
        City::create(['departament_id' => 6, 'name' => 'TURBACO', 'code' => '13836']);
        City::create(['departament_id' => 6, 'name' => 'TURBANA', 'code' => '13838']);
        City::create(['departament_id' => 6, 'name' => 'VILLANUEVA', 'code' => '13873']);
        City::create(['departament_id' => 6, 'name' => 'ALTOS DEL ROSARIO', 'code' => '13030']);
        City::create(['departament_id' => 6, 'name' => 'BARRANCO DE LOBA', 'code' => '13074']);
        City::create(['departament_id' => 6, 'name' => 'EL PEÑÓN', 'code' => '13268']);
        City::create(['departament_id' => 6, 'name' => 'REGIDOR', 'code' => '13580']);
        City::create(['departament_id' => 6, 'name' => 'RÍO VIEJO', 'code' => '13600']);
        City::create(['departament_id' => 6, 'name' => 'SAN MARTIN DE LOBA', 'code' => '13667']);
        City::create(['departament_id' => 6, 'name' => 'ARENAL', 'code' => '13042']);
        City::create(['departament_id' => 6, 'name' => 'CANTAGALLO', 'code' => '13160']);
        City::create(['departament_id' => 6, 'name' => 'MORALES', 'code' => '13473']);
        City::create(['departament_id' => 6, 'name' => 'SAN PABLO', 'code' => '13670']);
        City::create(['departament_id' => 6, 'name' => 'SANTA ROSA DEL SUR', 'code' => '13688']);
        City::create(['departament_id' => 6, 'name' => 'SIMITÍ', 'code' => '13744']);
        City::create(['departament_id' => 6, 'name' => 'ACHÍ', 'code' => '13006']);
        City::create(['departament_id' => 6, 'name' => 'MAGANGUÉ', 'code' => '13430']);
        City::create(['departament_id' => 6, 'name' => 'MONTECRISTO', 'code' => '13458']);
        City::create(['departament_id' => 6, 'name' => 'PINILLOS', 'code' => '13549']);
        City::create(['departament_id' => 6, 'name' => 'SAN JACINTO DEL CAUCA', 'code' => '13655']);
        City::create(['departament_id' => 6, 'name' => 'TIQUISIO', 'code' => '13810']);
        City::create(['departament_id' => 6, 'name' => 'CARMEN DE BOLÍVAR', 'code' => '13244']);
        City::create(['departament_id' => 6, 'name' => 'CÓRDOBA', 'code' => '13212']);
        City::create(['departament_id' => 6, 'name' => 'EL GUAMO', 'code' => '13248']);
        City::create(['departament_id' => 6, 'name' => 'MARÍA LA BAJA', 'code' => '13442']);
        City::create(['departament_id' => 6, 'name' => 'SAN JACINTO', 'code' => '13654']);
        City::create(['departament_id' => 6, 'name' => 'SAN JUAN NEPOMUCENO', 'code' => '13657']);
        City::create(['departament_id' => 6, 'name' => 'ZAMBRANO', 'code' => '13894']);

        City::create(['departament_id' => 7, 'name' => 'CHÍQUIZA', 'code' => '15232']);
        City::create(['departament_id' => 7, 'name' => 'CHIVATÁ', 'code' => '15187']);
        City::create(['departament_id' => 7, 'name' => 'CÓMBITA', 'code' => '15204']);
        City::create(['departament_id' => 7, 'name' => 'CUCAITA', 'code' => '15224']);
        City::create(['departament_id' => 7, 'name' => 'MOTAVITA', 'code' => '15476']);
        City::create(['departament_id' => 7, 'name' => 'OICATÁ', 'code' => '15500']);
        City::create(['departament_id' => 7, 'name' => 'SAMACÁ', 'code' => '15646']);
        City::create(['departament_id' => 7, 'name' => 'SIACHOQUE', 'code' => '15740']);
        City::create(['departament_id' => 7, 'name' => 'SORA', 'code' => '15762']);
        City::create(['departament_id' => 7, 'name' => 'SORACÁ', 'code' => '15764']);
        City::create(['departament_id' => 7, 'name' => 'SOTAQUIRÁ', 'code' => '15763']);
        City::create(['departament_id' => 7, 'name' => 'TOCA', 'code' => '15814']);
        City::create(['departament_id' => 7, 'name' => 'TUNJA', 'code' => '15001']);
        City::create(['departament_id' => 7, 'name' => 'TUTA', 'code' => '15837']);
        City::create(['departament_id' => 7, 'name' => 'VENTAQUEMADA', 'code' => '15861']);
        City::create(['departament_id' => 7, 'name' => 'CHISCAS', 'code' => '15180']);
        City::create(['departament_id' => 7, 'name' => 'CUBARÁ', 'code' => '15223']);
        City::create(['departament_id' => 7, 'name' => 'EL COCUY', 'code' => '15244']);
        City::create(['departament_id' => 7, 'name' => 'EL ESPINO', 'code' => '15248']);
        City::create(['departament_id' => 7, 'name' => 'GUACAMAYAS', 'code' => '15317']);
        City::create(['departament_id' => 7, 'name' => 'GÜICÁN', 'code' => '15332']);
        City::create(['departament_id' => 7, 'name' => 'PANQUEBA', 'code' => '15522']);
        City::create(['departament_id' => 7, 'name' => 'LABRANZAGRANDE', 'code' => '15377']);
        City::create(['departament_id' => 7, 'name' => 'PAJARITO', 'code' => '15518']);
        City::create(['departament_id' => 7, 'name' => 'PAYA', 'code' => '15533']);
        City::create(['departament_id' => 7, 'name' => 'PISBA', 'code' => '15550']);
        City::create(['departament_id' => 7, 'name' => 'BERBEO', 'code' => '15090']);
        City::create(['departament_id' => 7, 'name' => 'CAMPOHERMOSO', 'code' => '15135']);
        City::create(['departament_id' => 7, 'name' => 'MIRAFLORES', 'code' => '15455']);
        City::create(['departament_id' => 7, 'name' => 'PÁEZ', 'code' => '15514']);
        City::create(['departament_id' => 7, 'name' => 'SAN EDUARDO', 'code' => '15660']);
        City::create(['departament_id' => 7, 'name' => 'ZETAQUIRA', 'code' => '15897']);
        City::create(['departament_id' => 7, 'name' => 'BOYACÁ', 'code' => '15104']);
        City::create(['departament_id' => 7, 'name' => 'CIÉNEGA', 'code' => '15189']);
        City::create(['departament_id' => 7, 'name' => 'JENESANO', 'code' => '15367']);
        City::create(['departament_id' => 7, 'name' => 'NUEVO COLÓN', 'code' => '15494']);
        City::create(['departament_id' => 7, 'name' => 'RAMIRIQUÍ', 'code' => '15599']);
        City::create(['departament_id' => 7, 'name' => 'RONDÓN', 'code' => '15621']);
        City::create(['departament_id' => 7, 'name' => 'TIBANÁ', 'code' => '15804']);
        City::create(['departament_id' => 7, 'name' => 'TURMEQUÉ', 'code' => '15835']);
        City::create(['departament_id' => 7, 'name' => 'UMBITA', 'code' => '15842']);
        City::create(['departament_id' => 7, 'name' => 'VIRACACHÁ', 'code' => '15879']);
        City::create(['departament_id' => 7, 'name' => 'CHINAVITA', 'code' => '15172']);
        City::create(['departament_id' => 7, 'name' => 'GARAGOA', 'code' => '15299']);
        City::create(['departament_id' => 7, 'name' => 'MACANAL', 'code' => '15425']);
        City::create(['departament_id' => 7, 'name' => 'PACHAVITA', 'code' => '15511']);
        City::create(['departament_id' => 7, 'name' => 'SAN LUIS DE GACENO', 'code' => '15667']);
        City::create(['departament_id' => 7, 'name' => 'SANTA MARÍA', 'code' => '15690']);
        City::create(['departament_id' => 7, 'name' => 'BOAVITA', 'code' => '15097']);
        City::create(['departament_id' => 7, 'name' => 'COVARACHÍA', 'code' => '15218']);
        City::create(['departament_id' => 7, 'name' => 'LA UVITA', 'code' => '15403']);
        City::create(['departament_id' => 7, 'name' => 'SAN MATEO', 'code' => '15673']);
        City::create(['departament_id' => 7, 'name' => 'SATIVANORTE', 'code' => '15720']);
        City::create(['departament_id' => 7, 'name' => 'SATIVASUR', 'code' => '15723']);
        City::create(['departament_id' => 7, 'name' => 'SOATÁ', 'code' => '15753']);
        City::create(['departament_id' => 7, 'name' => 'SUSACÓN', 'code' => '15774']);
        City::create(['departament_id' => 7, 'name' => 'TIPACOQUE', 'code' => '15810']);
        City::create(['departament_id' => 7, 'name' => 'BRICEÑO', 'code' => '15106']);
        City::create(['departament_id' => 7, 'name' => 'BUENAVISTA', 'code' => '15109']);
        City::create(['departament_id' => 7, 'name' => 'CALDAS', 'code' => '15131']);
        City::create(['departament_id' => 7, 'name' => 'CHIQUINQUIRÁ', 'code' => '15176']);
        City::create(['departament_id' => 7, 'name' => 'COPER', 'code' => '15212']);
        City::create(['departament_id' => 7, 'name' => 'LA VICTORIA', 'code' => '15401']);
        City::create(['departament_id' => 7, 'name' => 'MARIPÍ', 'code' => '15442']);
        City::create(['departament_id' => 7, 'name' => 'MUZO', 'code' => '15480']);
        City::create(['departament_id' => 7, 'name' => 'OTANCHE', 'code' => '15507']);
        City::create(['departament_id' => 7, 'name' => 'PAUNA', 'code' => '15531']);
        City::create(['departament_id' => 7, 'name' => 'PUERTO BOYACÁ', 'code' => '15572']);
        City::create(['departament_id' => 7, 'name' => 'QUÍPAMA', 'code' => '15580']);
        City::create(['departament_id' => 7, 'name' => 'SABOYÁ', 'code' => '15632']);
        City::create(['departament_id' => 7, 'name' => 'SAN MIGUEL DE SEMA', 'code' => '15676']);
        City::create(['departament_id' => 7, 'name' => 'SAN PABLO BORBUR', 'code' => '15681']);
        City::create(['departament_id' => 7, 'name' => 'TUNUNGUÁ', 'code' => '15832']);
        City::create(['departament_id' => 7, 'name' => 'ALMEIDA', 'code' => '15022']);
        City::create(['departament_id' => 7, 'name' => 'CHIVOR', 'code' => '15236']);
        City::create(['departament_id' => 7, 'name' => 'GUATEQUE', 'code' => '15322']);
        City::create(['departament_id' => 7, 'name' => 'GUAYATÁ', 'code' => '15325']);
        City::create(['departament_id' => 7, 'name' => 'LA CAPILLA', 'code' => '15380']);
        City::create(['departament_id' => 7, 'name' => 'SOMONDOCO', 'code' => '15761']);
        City::create(['departament_id' => 7, 'name' => 'SUTATENZA', 'code' => '15778']);
        City::create(['departament_id' => 7, 'name' => 'TENZA', 'code' => '15798']);
        City::create(['departament_id' => 7, 'name' => 'ARCABUCO', 'code' => '15051']);
        City::create(['departament_id' => 7, 'name' => 'CHITARAQUE', 'code' => '15185']);
        City::create(['departament_id' => 7, 'name' => 'GACHANTIVÁ', 'code' => '15293']);
        City::create(['departament_id' => 7, 'name' => 'MONIQUIRÁ', 'code' => '15469']);
        City::create(['departament_id' => 7, 'name' => 'RÁQUIRA', 'code' => '15600']);
        City::create(['departament_id' => 7, 'name' => 'SÁCHICA', 'code' => '15638']);
        City::create(['departament_id' => 7, 'name' => 'SAN JOSÉ DE PARE', 'code' => '15664']);
        City::create(['departament_id' => 7, 'name' => 'SANTA SOFÍA', 'code' => '15696']);
        City::create(['departament_id' => 7, 'name' => 'SANTANA', 'code' => '15686']);
        City::create(['departament_id' => 7, 'name' => 'SUTAMARCHÁN', 'code' => '15776']);
        City::create(['departament_id' => 7, 'name' => 'TINJACÁ', 'code' => '15808']);
        City::create(['departament_id' => 7, 'name' => 'TOGÜÍ', 'code' => '15816']);
        City::create(['departament_id' => 7, 'name' => 'VILLA DE LEYVA', 'code' => '15407']);
        City::create(['departament_id' => 7, 'name' => 'AQUITANIA', 'code' => '15047']);
        City::create(['departament_id' => 7, 'name' => 'CUÍTIVA', 'code' => '15226']);
        City::create(['departament_id' => 7, 'name' => 'FIRAVITOBA', 'code' => '15272']);
        City::create(['departament_id' => 7, 'name' => 'GAMEZA', 'code' => '15296']);
        City::create(['departament_id' => 7, 'name' => 'IZA', 'code' => '15362']);
        City::create(['departament_id' => 7, 'name' => 'MONGUA', 'code' => '15464']);
        City::create(['departament_id' => 7, 'name' => 'MONGUÍ', 'code' => '15466']);
        City::create(['departament_id' => 7, 'name' => 'NOBSA', 'code' => '15491']);
        City::create(['departament_id' => 7, 'name' => 'PESCA', 'code' => '15542']);
        City::create(['departament_id' => 7, 'name' => 'SOGAMOSO', 'code' => '15759']);
        City::create(['departament_id' => 7, 'name' => 'TIBASOSA', 'code' => '15806']);
        City::create(['departament_id' => 7, 'name' => 'TÓPAGA', 'code' => '15820']);
        City::create(['departament_id' => 7, 'name' => 'TOTA', 'code' => '15822']);
        City::create(['departament_id' => 7, 'name' => 'BELÉN', 'code' => '15087']);
        City::create(['departament_id' => 7, 'name' => 'BUSBANZÁ', 'code' => '15114']);
        City::create(['departament_id' => 7, 'name' => 'CERINZA', 'code' => '15162']);
        City::create(['departament_id' => 7, 'name' => 'CORRALES', 'code' => '15215']);
        City::create(['departament_id' => 7, 'name' => 'DUITAMA', 'code' => '15238']);
        City::create(['departament_id' => 7, 'name' => 'FLORESTA', 'code' => '15276']);
        City::create(['departament_id' => 7, 'name' => 'PAIPA', 'code' => '15516']);
        City::create(['departament_id' => 7, 'name' => 'SAN ROSA VITERBO', 'code' => '15693']);
        City::create(['departament_id' => 7, 'name' => 'TUTAZÁ', 'code' => '15839']);
        City::create(['departament_id' => 7, 'name' => 'BETÉITIVA', 'code' => '15092']);
        City::create(['departament_id' => 7, 'name' => 'CHITA', 'code' => '15183']);
        City::create(['departament_id' => 7, 'name' => 'JERICÓ', 'code' => '15368']);
        City::create(['departament_id' => 7, 'name' => 'PAZ DE RÍO', 'code' => '15537']);
        City::create(['departament_id' => 7, 'name' => 'SOCHA', 'code' => '15757']);
        City::create(['departament_id' => 7, 'name' => 'SOCOTÁ', 'code' => '15755']);
        City::create(['departament_id' => 7, 'name' => 'TASCO', 'code' => '15790']);

        City::create(['departament_id' => 8, 'name' => 'FILADELFIA', 'code' => '17272']);
        City::create(['departament_id' => 8, 'name' => 'LA MERCED', 'code' => '17388']);
        City::create(['departament_id' => 8, 'name' => 'MARMATO', 'code' => '17442']);
        City::create(['departament_id' => 8, 'name' => 'RIOSUCIO', 'code' => '17614']);
        City::create(['departament_id' => 8, 'name' => 'SUPÍA', 'code' => '17777']);
        City::create(['departament_id' => 8, 'name' => 'MANZANARES', 'code' => '17433']);
        City::create(['departament_id' => 8, 'name' => 'MARQUETALIA', 'code' => '17444']);
        City::create(['departament_id' => 8, 'name' => 'MARULANDA', 'code' => '17446']);
        City::create(['departament_id' => 8, 'name' => 'PENSILVANIA', 'code' => '17541']);
        City::create(['departament_id' => 8, 'name' => 'ANSERMA', 'code' => '17042']);
        City::create(['departament_id' => 8, 'name' => 'BELALCÁZAR', 'code' => '17088']);
        City::create(['departament_id' => 8, 'name' => 'RISARALDA', 'code' => '17616']);
        City::create(['departament_id' => 8, 'name' => 'SAN JOSÉ', 'code' => '17665']);
        City::create(['departament_id' => 8, 'name' => 'VITERBO', 'code' => '17877']);
        City::create(['departament_id' => 8, 'name' => 'CHINCHINÁ', 'code' => '17174']);
        City::create(['departament_id' => 8, 'name' => 'MANIZALES', 'code' => '17001']);
        City::create(['departament_id' => 8, 'name' => 'NEIRA', 'code' => '17486']);
        City::create(['departament_id' => 8, 'name' => 'PALESTINA', 'code' => '17524']);
        City::create(['departament_id' => 8, 'name' => 'VILLAMARÍA', 'code' => '17873']);
        City::create(['departament_id' => 8, 'name' => 'AGUADAS', 'code' => '17013']);
        City::create(['departament_id' => 8, 'name' => 'ARANZAZU', 'code' => '17050']);
        City::create(['departament_id' => 8, 'name' => 'PÁCORA', 'code' => '17513']);
        City::create(['departament_id' => 8, 'name' => 'SALAMINA', 'code' => '17653']);
        City::create(['departament_id' => 8, 'name' => 'LA DORADA', 'code' => '17380']);
        City::create(['departament_id' => 8, 'name' => 'NORCASIA', 'code' => '17495']);
        City::create(['departament_id' => 8, 'name' => 'SAMANÁ', 'code' => '17662']);
        City::create(['departament_id' => 8, 'name' => 'VICTORIA', 'code' => '17867']);

        City::create(['departament_id' => 9, 'name' => 'ALBANIA', 'code' => '18029']);
        City::create(['departament_id' => 9, 'name' => 'BELÉN DE LOS ANDAQUIES', 'code' => '18094']);
        City::create(['departament_id' => 9, 'name' => 'CARTAGENA DEL CHAIRÁ', 'code' => '18150']);
        City::create(['departament_id' => 9, 'name' => 'CURRILLO', 'code' => '18205']);
        City::create(['departament_id' => 9, 'name' => 'EL DONCELLO', 'code' => '18247']);
        City::create(['departament_id' => 9, 'name' => 'EL PAUJIL', 'code' => '18256']);
        City::create(['departament_id' => 9, 'name' => 'FLORENCIA', 'code' => '18001']);
        City::create(['departament_id' => 9, 'name' => 'LA MONTAÑITA', 'code' => '18410']);
        City::create(['departament_id' => 9, 'name' => 'MILÁN', 'code' => '18460']);
        City::create(['departament_id' => 9, 'name' => 'MORELIA', 'code' => '18479']);
        City::create(['departament_id' => 9, 'name' => 'PUERTO RICO', 'code' => '18592']);
        City::create(['departament_id' => 9, 'name' => 'SAN JOSE DEL FRAGUA', 'code' => '18610']);
        City::create(['departament_id' => 9, 'name' => 'SAN VICENTE DEL CAGUÁN', 'code' => '18753']);
        City::create(['departament_id' => 9, 'name' => 'SOLANO', 'code' => '18756']);
        City::create(['departament_id' => 9, 'name' => 'SOLITA', 'code' => '18785']);
        City::create(['departament_id' => 9, 'name' => 'VALPARAISO', 'code' => '18860']);

        City::create(['departament_id' => 10, 'name' => 'AGUAZUL', 'code' => '85010']);
        City::create(['departament_id' => 10, 'name' => 'CHAMEZA', 'code' => '85015']);
        City::create(['departament_id' => 10, 'name' => 'HATO COROZAL', 'code' => '85125']);
        City::create(['departament_id' => 10, 'name' => 'LA SALINA', 'code' => '85136']);
        City::create(['departament_id' => 10, 'name' => 'MANÍ', 'code' => '85139']);
        City::create(['departament_id' => 10, 'name' => 'MONTERREY', 'code' => '85162']);
        City::create(['departament_id' => 10, 'name' => 'NUNCHÍA', 'code' => '85225']);
        City::create(['departament_id' => 10, 'name' => 'OROCUÉ', 'code' => '85230']);
        City::create(['departament_id' => 10, 'name' => 'PAZ DE ARIPORO', 'code' => '85250']);
        City::create(['departament_id' => 10, 'name' => 'PORE', 'code' => '85263']);
        City::create(['departament_id' => 10, 'name' => 'RECETOR', 'code' => '85279']);
        City::create(['departament_id' => 10, 'name' => 'SABANALARGA', 'code' => '85300']);
        City::create(['departament_id' => 10, 'name' => 'SÁCAMA', 'code' => '85315']);
        City::create(['departament_id' => 10, 'name' => 'SAN LUIS DE PALENQUE', 'code' => '85325']);
        City::create(['departament_id' => 10, 'name' => 'TÁMARA', 'code' => '85400']);
        City::create(['departament_id' => 10, 'name' => 'TAURAMENA', 'code' => '85410']);
        City::create(['departament_id' => 10, 'name' => 'TRINIDAD', 'code' => '85430']);
        City::create(['departament_id' => 10, 'name' => 'VILLANUEVA', 'code' => '85440']);
        City::create(['departament_id' => 10, 'name' => 'YOPAL', 'code' => '85001']);

        City::create(['departament_id' => 11, 'name' => 'CAJIBÍO', 'code' => '19130']);
        City::create(['departament_id' => 11, 'name' => 'EL TAMBO', 'code' => '19256']);
        City::create(['departament_id' => 11, 'name' => 'LA SIERRA', 'code' => '19392']);
        City::create(['departament_id' => 11, 'name' => 'MORALES', 'code' => '19473']);
        City::create(['departament_id' => 11, 'name' => 'PIENDAMÓ', 'code' => '19548']);
        City::create(['departament_id' => 11, 'name' => 'POPAYÁN', 'code' => '19001']);
        City::create(['departament_id' => 11, 'name' => 'ROSAS', 'code' => '19622']);
        City::create(['departament_id' => 11, 'name' => 'SOTARÁ', 'code' => '19760']);
        City::create(['departament_id' => 11, 'name' => 'TIMBÍO', 'code' => '19807']);
        City::create(['departament_id' => 11, 'name' => 'BUENOS AIRES', 'code' => '19110']);
        City::create(['departament_id' => 11, 'name' => 'CALOTO', 'code' => '19142']);
        City::create(['departament_id' => 11, 'name' => 'CORINTO', 'code' => '19212']);
        City::create(['departament_id' => 11, 'name' => 'MIRANDA', 'code' => '19455']);
        City::create(['departament_id' => 11, 'name' => 'PADILLA', 'code' => '19513']);
        City::create(['departament_id' => 11, 'name' => 'PUERTO TEJADA', 'code' => '19573']);
        City::create(['departament_id' => 11, 'name' => 'SANTANDER DE QUILICHAO', 'code' => '19698']);
        City::create(['departament_id' => 11, 'name' => 'SUÁREZ', 'code' => '19780']);
        City::create(['departament_id' => 11, 'name' => 'VILLA RICA', 'code' => '19845']);
        City::create(['departament_id' => 11, 'name' => 'GUAPI', 'code' => '19318']);
        City::create(['departament_id' => 11, 'name' => 'LOPEZ', 'code' => '19418']);
        City::create(['departament_id' => 11, 'name' => 'TIMBIQUÍ', 'code' => '19809']);
        City::create(['departament_id' => 11, 'name' => 'CALDONO', 'code' => '19137']);
        City::create(['departament_id' => 11, 'name' => 'INZÁ', 'code' => '19355']);
        City::create(['departament_id' => 11, 'name' => 'JAMBALÓ', 'code' => '19364']);
        City::create(['departament_id' => 11, 'name' => 'PAEZ', 'code' => '19517']);
        City::create(['departament_id' => 11, 'name' => 'PURACÉ', 'code' => '19585']);
        City::create(['departament_id' => 11, 'name' => 'SILVIA', 'code' => '19743']);
        City::create(['departament_id' => 11, 'name' => 'TORIBIO', 'code' => '19821']);
        City::create(['departament_id' => 11, 'name' => 'TOTORÓ', 'code' => '19824']);
        City::create(['departament_id' => 11, 'name' => 'ALMAGUER', 'code' => '19022']);
        City::create(['departament_id' => 11, 'name' => 'ARGELIA', 'code' => '19050']);
        City::create(['departament_id' => 11, 'name' => 'BALBOA', 'code' => '19075']);
        City::create(['departament_id' => 11, 'name' => 'BOLÍVAR', 'code' => '19100']);
        City::create(['departament_id' => 11, 'name' => 'FLORENCIA', 'code' => '19290']);
        City::create(['departament_id' => 11, 'name' => 'LA VEGA', 'code' => '19397']);
        City::create(['departament_id' => 11, 'name' => 'MERCADERES', 'code' => '19450']);
        City::create(['departament_id' => 11, 'name' => 'PATÍA', 'code' => '19532']);
        City::create(['departament_id' => 11, 'name' => 'PIAMONTE', 'code' => '19533']);
        City::create(['departament_id' => 11, 'name' => 'SAN SEBASTIÁN', 'code' => '19693']);
        City::create(['departament_id' => 11, 'name' => 'SANTA ROSA', 'code' => '19701']);
        City::create(['departament_id' => 11, 'name' => 'SUCRE', 'code' => '19785']);

        City::create(['departament_id' => 12, 'name' => 'BECERRIL', 'code' => '20045']);
        City::create(['departament_id' => 12, 'name' => 'CHIMICHAGUA', 'code' => '20175']);
        City::create(['departament_id' => 12, 'name' => 'CHIRIGUANÁ', 'code' => '20178']);
        City::create(['departament_id' => 12, 'name' => 'CURUMANÍ', 'code' => '20228']);
        City::create(['departament_id' => 12, 'name' => 'LA JAGUA DE IBIRICO', 'code' => '20400']);
        City::create(['departament_id' => 12, 'name' => 'PAILITAS', 'code' => '20517']);
        City::create(['departament_id' => 12, 'name' => 'TAMALAMEQUE', 'code' => '20787']);
        City::create(['departament_id' => 12, 'name' => 'ASTREA', 'code' => '20045']);
        City::create(['departament_id' => 12, 'name' => 'BOSCONIA', 'code' => '20060']);
        City::create(['departament_id' => 12, 'name' => 'EL COPEY', 'code' => '20238']);
        City::create(['departament_id' => 12, 'name' => 'EL PASO', 'code' => '20250']);
        City::create(['departament_id' => 12, 'name' => 'AGUSTÍN CODAZZI', 'code' => '20013']);
        City::create(['departament_id' => 12, 'name' => 'LA PAZ', 'code' => '20621']);
        City::create(['departament_id' => 12, 'name' => 'MANAURE', 'code' => '20443']);
        City::create(['departament_id' => 12, 'name' => 'PUEBLO BELLO', 'code' => '20570']);
        City::create(['departament_id' => 12, 'name' => 'SAN DIEGO', 'code' => '20750']);
        City::create(['departament_id' => 12, 'name' => 'VALLEDUPAR', 'code' => '20001']);
        City::create(['departament_id' => 12, 'name' => 'AGUACHICA', 'code' => '20011']);
        City::create(['departament_id' => 12, 'name' => 'GAMARRA', 'code' => '20295']);
        City::create(['departament_id' => 12, 'name' => 'GONZÁLEZ', 'code' => '20310']);
        City::create(['departament_id' => 12, 'name' => 'LA GLORIA', 'code' => '20383']);
        City::create(['departament_id' => 12, 'name' => 'PELAYA', 'code' => '20550']);
        City::create(['departament_id' => 12, 'name' => 'RÍO DE ORO', 'code' => '20614']);
        City::create(['departament_id' => 12, 'name' => 'SAN ALBERTO', 'code' => '20710']);
        City::create(['departament_id' => 12, 'name' => 'SAN MARTÍN', 'code' => '20770']);

        City::create(['departament_id' => 13, 'name' => 'ATRATO', 'code' => '27050']);
        City::create(['departament_id' => 13, 'name' => 'BAGADÓ', 'code' => '27073']);
        City::create(['departament_id' => 13, 'name' => 'BOJAYÁ', 'code' => '27099']);
        City::create(['departament_id' => 13, 'name' => 'EL CARMEN DE ATRATO', 'code' => '27245']);
        City::create(['departament_id' => 13, 'name' => 'LLORÓ', 'code' => '27413']);
        City::create(['departament_id' => 13, 'name' => 'MEDIO ATRATO', 'code' => '27425']);
        City::create(['departament_id' => 13, 'name' => 'QUIBDÓ', 'code' => '27001']);
        City::create(['departament_id' => 13, 'name' => 'RIO QUITO', 'code' => '27600']);
        City::create(['departament_id' => 13, 'name' => 'ACANDÍ', 'code' => '27006']);
        City::create(['departament_id' => 13, 'name' => 'BELÉN DE BAJIRA', 'code' => '27086']);
        City::create(['departament_id' => 13, 'name' => 'CARMÉN DEL DARIÉN', 'code' => '27150']);
        City::create(['departament_id' => 13, 'name' => 'RIOSUCIO', 'code' => '27615']);
        City::create(['departament_id' => 13, 'name' => 'UNGUÍA', 'code' => '27800']);
        City::create(['departament_id' => 13, 'name' => 'BAHÍA SOLANO', 'code' => '27075']);
        City::create(['departament_id' => 13, 'name' => 'JURADÓ', 'code' => '27372']);
        City::create(['departament_id' => 13, 'name' => 'NUQUÍ', 'code' => '27495']);
        City::create(['departament_id' => 13, 'name' => 'ALTO BAUDÓ', 'code' => '27025']);
        City::create(['departament_id' => 13, 'name' => 'BAJO BAUDÓ', 'code' => '27077']);
        City::create(['departament_id' => 13, 'name' => 'EL LITORAL DEL SAN JUAN', 'code' => '27250']);
        City::create(['departament_id' => 13, 'name' => 'MEDIO BAUDÓ', 'code' => '27430']);
        City::create(['departament_id' => 13, 'name' => 'CANTON DE SAN PABLO', 'code' => '27135']);
        City::create(['departament_id' => 13, 'name' => 'CERTEGUI', 'code' => '27160']);
        City::create(['departament_id' => 13, 'name' => 'CONDOTO', 'code' => '27205']);
        City::create(['departament_id' => 13, 'name' => 'ITSMINA', 'code' => '27361']);
        City::create(['departament_id' => 13, 'name' => 'MEDIO SAN JUAN', 'code' => '27450']);
        City::create(['departament_id' => 13, 'name' => 'NÓVITA', 'code' => '27491']);
        City::create(['departament_id' => 13, 'name' => 'RÍO FRÍO', 'code' => '27580']);
        City::create(['departament_id' => 13, 'name' => 'SAN JOSÉ DEL PALMAR', 'code' => '27660']);
        City::create(['departament_id' => 13, 'name' => 'SIPÍ', 'code' => '27745']);
        City::create(['departament_id' => 13, 'name' => 'TADÓ', 'code' => '27787']);
        City::create(['departament_id' => 13, 'name' => 'UNION PANAMERICANA', 'code' => '27810']);

        City::create(['departament_id' => 22, 'name' => 'CUCUTA', 'code' => '']);
    }
}
